name: deploy-container

on:
  workflow_dispatch:
  push:
    paths:
      - container/**

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: npm install
        working-directory: container
        
      - name: Build
        run: npm run build
        working-directory: container

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
